In [1]:
import os
import re
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader
import torch
from sklearn.model_selection import train_test_split
from pytorch_pretrained_bert import BertTokenizer

In [9]:
sentiment_list = ["pos", "neg"]
dataset_list = ["train", "test"]
data_path = "data"
senti2index = { item:idx for idx, item in enumerate(sentiment_list)}

In [6]:
sample_path = os.path.join(data_path, "train", "pos")
file_list = os.listdir(sample_path)

In [8]:
with open(os.path.join(sample_path, file_list[0])) as response:
    data = response.read()


Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High's satire is much closer to reality than is "Teachers". The scramble to survive financially, the insightful students who can see right through their pathetic teachers' pomp, the pettiness of the whole situation, all remind me of the schools I knew and their students. When I saw the episode in which a student repeatedly tried to burn down the school, I immediately recalled ......... at .......... High. A classic line: INSPECTOR: I'm here to sack one of your teachers. STUDENT: Welcome to Bromwell High. I expect that many adults of my age think that Bromwell High is far fetched. What a pity that it isn't!


In [14]:
df_list = []
for dataset in dataset_list:
    temp_doc = []
    temp_label = []
    for sentiment in sentiment_list:
        temp_path = os.path.join(data_path, dataset, sentiment)
        file_list = os.listdir(temp_path)
        for file in file_list:
            with open(os.path.join(temp_path, file), encoding="UTF8") as response:
                temp_data = response.read()
                temp_doc.append(temp_data)
                temp_label.append(senti2index[sentiment])
    data = {
        "sentence" : temp_doc,
        "label" : temp_label
    }
    df = pd.DataFrame(data)
    df_list.append(df)

In [15]:
for dataset, df in zip(dataset_list, df_list):
    df.to_csv(str(dataset) + ".csv", encoding="UTF8", index=False, header=False)

In [18]:
df_list[0]["label"].unique()

array([0, 1], dtype=int64)

In [2]:
data_path = "yahoo"

In [6]:
df = pd.read_csv(os.path.join(data_path, "train.csv"), header=None)

In [7]:
df.head()

0                                                  1  \
0  5  why doesn't an optical mouse work on a glass t...   
1  6       What is the best off-road motorcycle trail ?   
2  3             What is Trans Fat? How to reduce that?   
3  7                         How many planes Fedex has?   
4  7  In the san francisco bay area, does it make se...   

                                                   2  \
0                          or even on some surfaces?   
1                  long-distance trail throughout CA   
2  I heard that tras fat is bad for the body.  Wh...   
3  I heard that it is the largest airline in the ...   
4  the prices of rent and the price of buying doe...   

                                                   3  
0  Optical mice use an LED and a camera to rapidl...  
1  i hear that the mojave road is amazing!<br />\...  
2  Trans fats occur in manufactured foods during ...  
3  according to the www.fedex.com web site:\nAir ...  
4  renting vs buying depends on your goals. <br /...

In [6]:
a = torch.rand(2,10)

In [12]:
b = torch.zeros(2, 0)

In [13]:
b

tensor([], size=(2, 0))

In [10]:
torch.cat([a,b], dim=1)

tensor([[0.7743, 0.9372, 0.6013, 0.6396, 0.1535, 0.2089, 0.7534, 0.9875, 0.0549,
         0.2885, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8963, 0.3240, 0.5308, 0.9379, 0.2246, 0.1203, 0.8699, 0.7465, 0.3961,
         0.9962, 0.0000, 0.0000, 0.0000, 0.0000]])

In [14]:
torch.cat([a, b], dim=1)

tensor([[0.7743, 0.9372, 0.6013, 0.6396, 0.1535, 0.2089, 0.7534, 0.9875, 0.0549,
         0.2885],
        [0.8963, 0.3240, 0.5308, 0.9379, 0.2246, 0.1203, 0.8699, 0.7465, 0.3961,
         0.9962]])